### ISSUE TITLE
link-to encodes & in href

### ISSUE THREAD

**Issue by mvitz** [weavejester/hiccup#111]
It seems hiccup escapes the URI given to link-to. If this is intended behaviour you can close this issue but at least for me this behaviour was unexpected.

Expected:

```
(use 'hiccup.element)
(use 'hiccup.core)
(html (link-to "/foobar?foo=bar&foo=baz")) #-> "<a href=\"/foobar?foo=bar&foo=baz\"></a>"
```

Actual:

```
(use 'hiccup.element)
(use 'hiccup.core)
(html (link-to "/foobar?foo=bar&foo=baz")) #-> "<a href=\"/foobar?foo=bar&amp;foo=baz\"></a>"
```

**Comment by weavejester** [comment]
Yes, that's the correct behavior.

It's worth noting that HTML5 now allows for bare ampersands in certain attributes, and browsers have coped with this for a while how. However, using bare ampersands leads to ambiguities in certain cases. For instance, what if you had a URI like `/foo=&amp;`?
