### ISSUE TITLE
cross hiccup & mustache ideas

### ISSUE THREAD

**Issue by niquola** [weavejester/hiccup#115]
@weavejester, what is your opinion about logic-less templates like mustache?
Is it possible to cross this ideas with hiccup and save data nature of templates:

```clojure
[:ul
  ['for ['x 'xs]
     [:li  ['link-to ['x :uri] ['x :title]]]]

;; compiled into
(fn [xs] 
   [:ul
     (for [x xs] 
        [:li (link-to (x :uri) (x :title))])])

;; link-to and for could be registered in compiler
```

**Comment by weavejester** [comment]
If you want to have a go at writing a library like this, go ahead. I don't think it should be part of the Hiccup library, though.

**Comment by niquola** [comment]
Ok, thx
