### ISSUE TITLE
Add ability to generate an output without a tag

### ISSUE THREAD

**Issue by mrchaarlie** [weavejester/hiccup#133]
Perhaps it's not intended, or I cannot figure this out, but I should be able to output something without having to wrap it in a tag.

**Comment by weavejester** [comment]
Could you explain a little more what you mean by this? Hiccup can already output raw text, or lists of elements:

```clojure
user=> (html "hello")
"hello"
user=> (html (list [:span "foo"] [:span "bar"]))
"<span>foo</span><span>bar</span>"
```
