### ISSUE TITLE
Support reagent-style map style attributes

### ISSUE THREAD

**Issue by pesterhazy** [weavejester/hiccup#136]
Reagent supports an extension to hiccup's syntax:

```
[:div {:style {:color :red, :margin-top "75px"}} "text"]
```

as a more readable version of

```
[:div {:style "color: red; margin-top: 75px"} "text"]
```

`:margin-top 75` also works. This is a useful extension and quite natural. It's also mildly surprising for people coming from reagent (back) to hiccup that this doesn't work in hiccup pure.

Would you be interested in such an extension?

**Comment by weavejester** [comment]
This is reasonable, as long as string values are still supported for styles to retain backward compatibility.

**Comment by weavejester** [comment]
Fixed by #139.

**Comment by theronic** [comment]
Which Hiccup version supports style attributes as a map?

**Comment by theronic** [comment]
Answer: 2.0.0-alpha1

This just bit me but I've asked before :) https://github.com/weavejester/hiccup/pull/139#issuecomment-355088387
