### ISSUE TITLE
Output is incorrect if attribute contains colon

### ISSUE THREAD

**Issue by Jarzka** [weavejester/hiccup#138]
I have the following hiccup form
[:use {:xlink:href (str "#" name)}]

This incorrectly outputs as an empty use tag without any attributes.

It seems that if :xlink:href is replaced with :href it works, however Firefox and iPad require to use the correct attribute xlink:href

**Comment by Jarzka** [comment]
Nevermind, :xlinkHref works.

**Comment by zerg000000** [comment]
I have tried test case like below, it passes

```
(is (= (str (html [:xml {:a:b "1", :b "2"}])) "<xml a:b=\"1\" b=\"2\"></xml>"))
```

how to reproduce your case?
