### ISSUE TITLE
Escape single quote with something else than &apos; ?

### ISSUE THREAD

**Issue by Jarzka** [weavejester/hiccup#146]
When a single quote character (') is escaped with escape-html function, the end result is `&apos;`. This is not an official entity in HTML. We noticed, for example, that when HTML mail is sent with escaping, it does render correctly in Outlook (Outlook renders single quote characters as text `&apos;` instead of ';

According to [this discussion](https://stackoverflow.com/questions/2083754/why-shouldnt-apos-be-used-to-escape-single-quotes), `&#39;` should be prefered.

**Comment by weavejester** [comment]
It already does, as long as the `*html-mode*` is set to the legacy `:sgml` format.

There are three values `*html-mode*` can be: `:xhtml`, for HTML in XML format, `:html` for HTML5 and generally anything supported by a browser, and `:sgml` for HTML4 and earlier.

`&apos;` is an official entity in HTML5, just not in HTML4 or earlier.
