### ISSUE TITLE
Multiple files input cannot be represented in hiccup

### ISSUE THREAD

**Issue by orolle** [weavejester/hiccup#148]
`<input type="file" name="img" multiple></input>`

I could not represented the above html in hiccup because "multiple" is not a regular attribute. 
I also tried http://html2hiccup.buttercloud.com/ to convert it into hiccup but it also failed. 

`[:input {:multiple :type "file"} ]`  Error: Map literals must contain an even number of forms.
`[:input {:multiple nil :type "file"} ]` False: Translates to `<input type="file"></input>`

**Comment by weavejester** [comment]
```clojure
[:input {:multiple true, :type "file"}]
```

**Comment by orolle** [comment]
Thanks a lot! That worked!
:+1:
