### ISSUE TITLE
URL in parameter shouldn't be escaped

### ISSUE THREAD

**Issue by piotr-yuxuan** [weavejester/hiccup#155]
According to the doc:
``` markdown
Creates a URI instance from a variable list of arguments and an optional parameter map as the last argument. For example:

(url "/group/" 4 "/products" {:page 9})
  => "/group/4/products?page=9"
```
So I did:
``` clojure
(hiccup.core/html
  [:div [:script {:type "application/javascript"
                  :src (hiccup.util/url "/group/" 4 "/products" 
                                        {:page 9 :num_ber 3})}]])
;; => "<div><script src=\"/group/4/products?page=9&amp;num_ber=3\" type=\"application/javascript\"></script></div>"
```

This is with `[hiccup "1.0.5"]` as shown in the README.md. I've had some attempts with hiccup2 alpha2, to no avails.

Any suggestion?

**Comment by weavejester** [comment]
Why do you think attributes shouldn't contain character entities?

**Comment by weavejester** [comment]
> How can you provide a URL with query parameters without plain `&` as a separator?

You use `&amp;`, as Hiccup does. Character entities in attributes are resolved when rendering the page, so this link:

```html
<a href="http://example.com/search?q=foo&amp;page=1">foo</a>
```

Will link to `http://example.com/search?q=foo&page=1`.

You *can* also use `&` directly, but you need to ensure that you don't accidentally include a character entity. Overall it's safer just to escape all unsafe characters as the browser will resolve them when the DOM is parsed.

**Comment by piotr-yuxuan** [comment]
Here is what Firefox sees when navigating to `http://example.com/search?q=foo&page=1`

<img width="102" alt="screenshot 2019-01-28 at 00 47 22" src="https://user-images.githubusercontent.com/3686502/51808606-5780ac00-2296-11e9-8f0f-4b6058516803.png">

That led me to open this issue.

**Comment by piotr-yuxuan** [comment]
👍
