### ISSUE TITLE
why generated html is cluttered together?

### ISSUE THREAD

**Issue by introom** [weavejester/hiccup#161]
for code like this:
```
(defn page-head []
  [:head
   [:meta {:charset "utf-8"}]
   [:meta {:name "viewport"
           :content "width=device-width, initial-scale=1"}]
   ;; we first include vendor css, then our own css
   (include-css "/assets/bulma/css/bulma.min.css" (:css-path cfg))])
```

the generated html is cluttered in a single line:
`<html><head><meta charset="utf-8"><meta content="width=device-width, initial-scale=1" name="viewport"><link href="/assets/bulma/css/bulma.min.css" rel="stylesheet" type="text/css"><link href="/css/site.css" rel="stylesheet" type="text/css"></head><body class="body-container"><div id="app">...</body></html>`

**Comment by weavejester** [comment]
It's faster to generate without formatting. Adding optional formatting is possible, but it's a lot of work and no-one has submitted a PR to that effect. If you want better formatting, then running the output through a HTML formatting tool is probably your best bet.
