### ISSUE TITLE
Hi How to write hiccup code for observable embed code in Roam ? 

### ISSUE THREAD

**Issue by steveyang331** [weavejester/hiccup#166]
1. visit this link https://observablehq.com/@d3/sketchy-earth
2. get embed code  :
![image](https://user-images.githubusercontent.com/16850883/80863897-dcd0e880-8cb1-11ea-8492-397ba1d1734e.png)

`<div id="observablehq-476e08a1"></div> <script type="module"> import {Runtime, Inspector} from "https://cdn.jsdelivr.net/npm/@observablehq/runtime@4/dist/runtime.js"; import define from "https://api.observablehq.com/@d3/sketchy-earth.js?v=3"; const inspect = Inspector.into("#observablehq-476e08a1"); (new Runtime).module(define, name => (name === "chart") && inspect()); </script>`

3. transfer hiccup code 

`:hiccup [:div {:id "observablehq-3a3c7c79"} {:script {:type "module"} {"import {Runtime, Inspector} from "https://cdn.jsdelivr.net/npm/@observablehq/runtime@4/dist/runtime.js"; import define from "https://api.observablehq.com/@d3/sketchy-earth.js?v=3"; const inspect = Inspector.into("#observablehq-3a3c7c79"); (new Runtime).module(define, name => (name === "chart") && inspect());"}} ]`

![image](https://user-images.githubusercontent.com/16850883/80863920-feca6b00-8cb1-11ea-8e8d-8bc10e6f9175.png)

Result failed. 

Please help convert right hiccup code. 

I can't figure it out where is it wrong . 

Thanks.

**Comment by weavejester** [comment]
The Hiccup code you've posted doesn't match up to the HTML you've posted, and the syntax has several problems. Quotes in strings should be escaped, the `:script` element should come after the `:div`, and the `:script` element should be a vector, not a map. It should be:

```clojure
(list
 [:div {:id "observablehq-476e08a1"}]
 [:script {:type "module"}
  "import {Runtime, Inspector} from \"https://cdn.jsdelivr.net/npm/@observablehq/runtime@4/dist/runtime.js\"; import define from \"https://api.observablehq.com/@d3/sketchy-earth.js?v=3\"; const inspect = Inspector.into(\"#observablehq-476e08a1\"); (new Runtime).module(define, name => (name === \"chart\") && inspect());"])
```

**Comment by steveyang331** [comment]
> ```clojure
> (list
> ```

Thank you so much for help !

That code is run on Roam.  
But 
![image](https://user-images.githubusercontent.com/16850883/80897117-1d6b4900-8d28-11ea-8909-200aba24437d.png)

**Comment by steveyang331** [comment]
I found solution 

`:hiccup [:iframe {     :height 500     :width 600     :srcdoc "<div id=\"observablehq-b9a930e6\"></div> <script type=\"module\"> import {Runtime, Inspector} from \"https://cdn.jsdelivr.net/npm/@observablehq/runtime@4/dist/runtime.js\"; import define from \"https://api.observablehq.com/d/eceaa744227c4fea.js?v=3\"; const inspect = Inspector.into(\"#observablehq-b9a930e6\"); (new Runtime).module(define, name => (   name === \"vegaPetalsWidget\"   || name === 'viewof sepalLengthLimits'   || name === 'viewof sepalWidthLimits') && inspect()); </script> "}]
`
