### ISSUE TITLE
Null pointer exception with `:class` attribute containing vector nil

### ISSUE THREAD

**Issue by kwrooijen** [weavejester/hiccup#168]
The following fails with a null pointer exception

```
(hiccup/html [:div.foo {:class [nil]}])
```

I'll check this out (hopefully) tomorrow

**Comment by weavejester** [comment]
`(map name classes)` probably needs to be changed to `(map to-str classes)`.

**Comment by kwrooijen** [comment]
`to-str` causes the `nil`s to become empty string. Then when we join them we get extra spaces. Not sure if this is desirable? Maybe it's better to filter the `nil`s instead.

**Comment by weavejester** [comment]
Joining to get multiple spaces is fine. The output from Hiccup is not prettified.
