### ISSUE TITLE
Historical question: Why is hiccup called hiccup?

### ISSUE THREAD

**Issue by harold** [weavejester/hiccup#188]
Hello, out of curiosity, does anyone know the origin of  the name 'hiccup' for this library?

Going to do some writing to promote these awesome ideas, and would like to include some historical background. Thanks!

**Comment by weavejester** [comment]
You know, that's the first time anyone's asked me that.

It was because it was a library for representing **H**TML **I**n **C**lojure, which makes the acronym "HIC", and from that "Hiccup" was derived.

**Comment by harold** [comment]
That's outstanding.

So the 'up' coinciding with 'markup' is just a happy accident, then?

Using edn (vectors with first element keyword and optional section element map, ...) to represent html (sgml) is profound; strings with angle brackets, equal signs, and quotes are much less computable. I will mix my efforts with spreading this insight.

Thanks, and take care.
