### ISSUE TITLE
link to api docs in project description is broken

### ISSUE THREAD

**Issue by msladecek** [weavejester/hiccup#189]
The links points to `github.com` but it should be `github.io`

broken: https://weavejester.github.com/hiccup
working: https://weavejester.github.io/hiccup/

![image](https://user-images.githubusercontent.com/7304317/137480374-cef2426d-10e4-4769-8379-508ecb2dee1a.png)

**Comment by weavejester** [comment]
Fixed by #186.

**Comment by msladecek** [comment]
I meant this one :smile: 


![image](https://user-images.githubusercontent.com/7304317/150420977-7d7d1c1c-697c-44a1-b37d-d27fe59733ba.png)

**Comment by weavejester** [comment]
Oh, whoops! Fixed.
