### ISSUE TITLE
*escape-strings?*

### ISSUE THREAD

**Issue by simon-brooke** [weavejester/hiccup#197]
This isn't a bug report so much as a request for guidance.

In the current master version (1.0.5) of `hiccup.util`, a dynamic variable `*escape-strings?*` is declared. However, it doesn't appear to be present in the 1.0.5 jar file as downloaded from clojars.org.

There is a function `hiccup.compiler/escape-html` which reads this variable, and, if it is bound to true (as by default it is), calls a function `hiccup.util/escape-html` on its argument.

I'm currently having a problem with hiccup rendering single quote characters within JavaScript strings as `&apos`, thus:

```clojure

(defn all-entries-cell
  [^Integer row ^Boolean ltr? ^Boolean long?]
  [:td {:class "play-row"
        :onclick (format "new Audio('audio/%s%s%02d_MP3WRAP.mp3').play();"
                         (if ltr? "ltr" "rtl")
                         (if long? "long" "short")
                         (inc row))}
   (str "Play " (if ltr? "LTR" "RTL"))])

(html (all-entries-cell 1 true true))
```

returns
```
"<td class=\"play-row\" onclick=\"new Audio(&apos;audio/ltrlong02_MP3WRAP.mp3&apos;).play();\">Play LTR</td>"
```

As it is `hiccup.util/escape-html` which performs the `&apos;` substitution, I had assumed that if I bound `*escape-strings?*` to false, this would cure my problem, but in fact with the 1.0.5 as downloaded from clojars it doesn't:

```clojure
(binding [hiccup.util/*escape-strings?* false]
  (html (all-entries-cell 1 true true)))
```
results in

```
Syntax error compiling var at (/tmp/form-init1525591202338818231.clj:1:1).
Unable to resolve var: hiccup.util/*escape-strings?* in this context
```

When, however, I build the current master version from source, I get a new jar file `hiccup-2.0.0-alpha2.jar`. This contains a new namespace, `hiccup2.core`, and the docstring for `hiccup2.core/html` says that it accepts an options map within which there is a key `:escape-strings?`. 

Again, I assumed that if I passed this as false, I'd get the result I wanted, but, again, I don't:

```clojure
(str (hiccup2.core/html {:escape-strings? false} (all-entries-cell 1 true true)))
```

results in

```
"<td class=\"play-row\" onclick=\"new Audio(&apos;audio/ltrlong02_MP3WRAP.mp3&apos;).play();\">Play LTR</td>"
```

So, my questions:

1. is it an oversight that `hiccup.util/*escape-strings?*` is missing from the 1.0.5 jar on clojars.org?
2. if so, would a patch to allow a new 1.0.6 version with the variable present to be compiled be accepted?
3. if not, is it the intention that the `:escape-strings?` option key in 2.0.0, given the value `false`, should disable `&apos;` substitution?
4. if so, would a patch to allow a new 2.0.0-alpha3 version with the options key `:escape-strings?` working to be compiled be accepted?

**Comment by weavejester** [comment]
> In the current master version (1.0.5) of `hiccup.util`, a dynamic variable `*escape-strings?*` is declared. However, it doesn't appear to be present in the 1.0.5 jar file as downloaded from clojars.org.

The `*escape-strings?*` variable was introduced in 2.0.0-alpha1. The master branch is tracking 2.0.0, not 1.0.5.

> There is a function `hiccup.compiler/escape-html` which reads this variable, and, if it is bound to true (as by default it is), calls a function `hiccup.util/escape-html` on its argument.
> 
> I'm currently having a problem with hiccup rendering single quote characters within JavaScript strings as `&apos`

Why is that a problem?

> So, my questions:
> 
>     1. is it an oversight that `hiccup.util/*escape-strings?*` is missing from the 1.0.5 jar on clojars.org?

No, because that variable was added laater.

>     2. if so, would a patch to allow a new 1.0.6 version with the variable present to be compiled be accepted?

No, because that variable ties into the 2.0.0 changes around raw strings.

>     3. if not, is it the intention that the `:escape-strings?` option key in 2.0.0, given the value `false`, should disable `&apos;` substitution?

I believe that attributes are always escaped, as I don't know of any reason not to.

>     4. if so, would a patch to allow a new 2.0.0-alpha3 version with the options key `:escape-strings?` working to be compiled be accepted?

Working for attributes you mean? You'd need to provide a reason for allowing unescaped attribute values.
