### ISSUE TITLE
Parameters for iframe src attribute

### ISSUE THREAD

**Issue by jrootham** [weavejester/hiccup#200]
There is no obvious way to put parameters on the src attribute of an iframe.

**Comment by weavejester** [comment]
I'm afraid I don't understand the question. Can you give an example of the HTML you're trying to produce?

**Comment by jrootham** [comment]
<iframe src="page.html?arg1=1&arg2=a"></iframe>

**Comment by weavejester** [comment]
That would be written in Hiccup as:

```clojure
[:iframe {:src "page.html?arg1=1&arg2=a"}]
```

**Comment by jrootham** [comment]
Yes, that is possible.  I was hoping to write [:iframe {:src "page.html" :query-params {"arg1" "1", "arg2" "a"}}]

I was thinking that this would be more like form-to, but I just realized that the parameter string there is constructed by the browser, so this would be a new thing for hiccup.

I would still like to propose it as a new feature.  Is there a particular format you would like to see proposed features described in?

**Comment by jrootham** [comment]
In particular, would you like me to do a pull request?

**Comment by weavejester** [comment]
You can use the `hiccup.util/url` function for that:

```clojure
(require '[hiccup.core :as h])
(require '[hiccup.util :as u])

(h/html [:iframe {:src (u/url "page.html" {:arg1 1, :arg2 "a"})}])
```

With regards to pull requests, it's usually best to first raise an issue so the feature can be discussed, before starting coding.

**Comment by jrootham** [comment]
D'oh, I obviously failed to RTFM.

**Comment by jrootham** [comment]
See RTFM
