### ISSUE TITLE
Ambiguity in using form-to

### ISSUE THREAD

**Issue by KnowledgeGarden** [weavejester/hiccup#25]
The example: (form-to [method action] uses :put "/post" and suggests that "/post" is a route. It's not clear what that route stands for. If I use defpage "/post", then I get the "missing page" message when http://localhost:8080/post fires based on the form (a login form). If I click refresh, the code fires, but not when called programmatically.  What am I missing?  Many thanks.

**Comment by Aeyk** [comment]
It appears now[1] that browser compatibility for the rest of the HTTP  verbs has caught up to RESTful design. 
Should there be a way to use native browser HTTP verbs when using form-to.?

https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods#browser_compatibility
