### ISSUE TITLE
could you add an optional "options" parameter to include-css?

### ISSUE THREAD

**Issue by jlgeering** [weavejester/hiccup#72]
(include-css & styles) => (include-css options & styles) like (xhtml options & contents)?

this would allow us to write

(include-css  {:media "screen, projector, print"} "/css/app.css")

instead of

[:link {:href "/css/app.css" :media "screen, projector, print" :rel "stylesheet" :type "text/css"} ]

cheers
JL

**Comment by bostonaholic** [comment]
Any idea when allowing `{:media "screen"}` for `include-css` will be released?

**Comment by weavejester** [comment]
Hiccup currently isn't that far up my priority list, I'm afraid. It might be a while until I get around to completing the 2.0 branch.
